/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegacyRouteImport } from './routes/$legacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ConversationConversationIdRouteImport } from './routes/conversation.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/$legacy',
  path: '/$legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationConversationIdRoute =
  ConversationConversationIdRouteImport.update({
    id: '/conversation/$conversationId',
    path: '/conversation/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$legacy': typeof LegacyRoute
  '/settings': typeof SettingsRoute
  '/conversation/$conversationId': typeof ConversationConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$legacy': typeof LegacyRoute
  '/settings': typeof SettingsRoute
  '/conversation/$conversationId': typeof ConversationConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$legacy': typeof LegacyRoute
  '/settings': typeof SettingsRoute
  '/conversation/$conversationId': typeof ConversationConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$legacy' | '/settings' | '/conversation/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$legacy' | '/settings' | '/conversation/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/$legacy'
    | '/settings'
    | '/conversation/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegacyRoute: typeof LegacyRoute
  SettingsRoute: typeof SettingsRoute
  ConversationConversationIdRoute: typeof ConversationConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$legacy': {
      id: '/$legacy'
      path: '/$legacy'
      fullPath: '/$legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$conversationId': {
      id: '/conversation/$conversationId'
      path: '/conversation/$conversationId'
      fullPath: '/conversation/$conversationId'
      preLoaderRoute: typeof ConversationConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegacyRoute: LegacyRoute,
  SettingsRoute: SettingsRoute,
  ConversationConversationIdRoute: ConversationConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
